name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      
      # Run ESLint auto-fix
      - run: pnpm run fix:eslint || true
      
      # Run Prettier format  
      - run: pnpm run format

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27